#! /bin/sh

# this script should be run immediately after the rpi has
# maximised the sdcard space, ie after the first boot.
# it installs subversion and sets up rpi to boot to console and then runs init-rpi
# through systemd service. init-rpi only runs once and does
# the rest of the setup.

# this is done so user pi is not active
# and usermod and groupmod can be run.

usage() {
	echo "-m disk label for debhome				default: ${DEBHOMELABEL}";
	echo "-s disk label for svn      				default: ${SVNLABEL}";
	echo "-S svn destination					default: none";
   	echo "-R reboot                                         default: no reboot";
	echo "-h help"
	exit 0
}
# function to log error, print error and exit
# parameter passed: error string
exitonerror() {
	echo "$1" | tee -a ${LOGFILE}
	exit 1;
}

setupservice() {
	# setup init-rpi.service to launch init-rpi on reboot
	# network must be up and running
	echo "[Unit]
	Description=init-rpi.service reboot raspberry pi and then initialise rpi once.
	BindsTo=multi-user.target
	After=multi-user.target

	[Service]
	Type=simple
	ExecStart=/bin/bash /usr/local/bin/init-rpi $*

	[Install]
	WantedBy=multi-user.target" > /etc/systemd/system/init-rpi.service

	# set mode for init-rpi.service
	chmod 0644 /etc/systemd/system/init-rpi.service

	# enable the service for the next boot
	systemctl enable init-rpi
}

####################################################
# function to check for svn or debhome
# this function will mount the correct disk drive
# if they are on a  disk drive LABEL.
# the function will exit  on error if not found
# parameters passed: disk_label, root directory of svn | root directory of debhome
####################################################
mountresource () {
	# check if the disk label is attached
	DEVICE=`blkid -L "$1"`

	if test "$?" -ne 0; then
		exitonerror "$1 is not attached"
	else
		# check if device is mounted and where
		grep "${DEVICE}" /etc/mtab
		if test $? -eq 0; then
			MOUNTPT=`grep "${DEVICE}" /etc/mtab | cut -d " " -f2`
			# disk is  mounted at MOUNTPT
			# unmount if MOUNTPT is not /mnt/disk_label
			if test "${MOUNTPT}" != "/mnt/$1"; then
				echo "unmounting ${MOUNTPT}"
				umount "${MOUNTPT}"
			fi
		fi
	fi

	# make the mount directory if it does not exist
	# make the directory and set the ownership
	test -d "/mnt/$1" || mkdir "/mnt/$1"
	#  if disk not mounted, mount it
	findmnt "/mnt/$1"
	if test "$?" -ne 0; then
		# mount it
		mount -L "$1" "/mnt/$1"
		# set mounted flag
		test $? -eq 0 || exitonerror "could not mount $"
	fi

	# check if svn | debhome is accessible
	if test ! -d "/mnt/$1/$2"; then
		# svn or archive does not exist
		echo "/mnt/$1/$2 not found"
		echo "unmounting /mnt/$1"
		umount "/mnt/$1"
		exitonerror "/mnt/$1/$2 not found"
	fi
	return 0;
}

# defaults, links
# /mnt/debhome    -> /mnt/DEBHOMELABEL/debhome
# /mnt/svn        -> /mnt/SVNLABEL/svn
# the links cannot be changed, the mountpoints can be changed
# DEBHOMELABEL, SVNLABEL
# are the labels of the disks containing debhome, svn and
# are all mounted at /mnt/LABEL

# only for raspberry pi
DEBHOMELABEL="ad64"
SVNLABEL="ad64"
REBOOT="false"
LOGFILE="/tmp/init-rpi-first.log"

# rm log file
rm -f ${LOGFILE}

# parameter S destinstion of svn is
# only used in init-rpi, not in this script
# svndestination is only used by init-rpi
# it must be defined here as it is passed to init-rpi
while getopts RS:m:s:r:h opt
do
	case ${opt} in
		m) DEBHOMELABEL="${OPTARG}";;
		s) SVNLABEL="${OPTARG}";;
		S) SVNDESTINATION="${OPTARG}";;
		R) REBOOT="true";;
		h) usage;;
		\?) usage;;
	esac
done

# check if subversion repository exists
mountresource "${SVNLABEL}" "svn"

################################
# check debhome repository exists
###############################
mountresource "${DEBHOMELABEL}" "debhome"

#####################################
# init-rpi must to be copied to /usr/local/bin
# find init-rpi
# look in current dir, usr/local/bin, prompt
# exit if init-rpi not found
#####################################
if test -f "/usr/local/bin/init-rpi"; then
	# found init-rpi
	echo "found /usr/local/bin/init-rpi"
elif test -f "init-rpi"; then
	# look in current directory
	echo "found init-rpi"
	cp -v init-rpi /usr/local/bin/

else
	# prompt for init-rpi
	echo "Enter the path of init-rpi"
	read INITP
	if test -f "${INITP}/init-rpi"; then
		if test "/usr/local/bin" != "${INITP}"; then
			cp -v "${INITP}/init-rpi" "/usr/local/bin/"
		fi
	else
		# file not found
		exitonerror "${INITP}/init-rpi not found"
	fi
fi


######################################
# install subversion if it is not installed
# this used to be in init-rpi
# solves a lot of problems installing it first
######################################
dpkg-query -W subversion > /dev/null 2>&1
if test $? -ne 0; then
	apt update
	test $? -eq 0 || exitonerror "error from apt update"

	apt -y install subversion
	test $? -eq 0 || exitonerror "error installing subversion"
fi

#############################################
# setup console boot, hostname timezone,
# console fonts, keyboard, splash screen,
# disable overscan
#############################################
# set the rpi to boot to console and no autologin
systemctl set-default multi-user.target
ln -fs /lib/systemd/system/getty@.service /etc/systemd/system/getty.target.wants/getty@tty1.service
if test -e /etc/systemd/system/getty@tty1.service.d/autologin.conf; then
	rm /etc/systemd/system/getty@tty1.service.d/autologin.conf
fi

# set the time and zone
timedatectl set-timezone Africa/Johannesburg

# set hostname
hostnamectl set-hostname rpi
# change it in /etc/hosts
sed -i -e 's/raspberrypi/rpi/' /etc/hosts

# setup default console with Terminus
cd /etc/default
sed -i -e 's/FONTFACE=\".*\"/FONTFACE="Terminus"/' \
       -e 's/FONTSIZE=\".*\"/FONTSIZE="16x32"/' /etc/default/console-setup

# setup keyboard
sed -i -e 's/XKBLAYOUT=\".*\"/XKBLAYOUT="za"/' /etc/default/keyboard
setupcon --save

# remove splash screen and make boot verbose
sed -i -e 's/quiet splash plymouth.ignore-serial-consoles//' /boot/cmdline.txt

# disable overscan to remove border in x windows
sed -i -e 's/^#disable_overscan/disable_overscan/' /boot/config.txt

# disable wi-fi and bluetooth
# prevent multiple copies
sed -i -e '/# disable wifi/,/disable-bt/d' /boot/config.txt
sed -i -e '/^# Additional overlays/a\# disable wifi\
dtoverlay=disable-wifi\
#disable bluetooth\
dtoverlay=disable-bt' /boot/config.txt

#####################################
# launch service init-rpi if necessary
# create the init-rpi service
# the svn destination and/or debhome label may have changed
# so they must be passed to init-rpi
# since a reboot will occur
###################################
# only use init-rpi.service if user robert
# does not exist
getent passwd robert > /dev/null 2>&1
RC=$?
echo "setupservice $*"
test ${RC} -ne 0 && setupservice $*

############################################
# reboot if it is necessary
# only necessary if pi was changed to robert
############################################
if test "${REBOOT}" = "true" && test ${RC} -ne 0; then
	shutdown -r now
else
	# excute init-rpi
	/usr/local/bin/init-rpi $*

fi
