#!/usr/bin/bash

##################################################
# get status install or upgrade from /tmp/initialise-linux-status
# which was created by preinst
# for upgrade (the key may or may not have changed)
#     get the current key id (old key)
#     get the new key id
#     if the new key id is not in the keyring
#        delete the current key id
#        import the new key
#     else
#        the new key = old key do nothing
# for install (the first install)
#     get the current key id
#     import the secret key
# sign the repository
# after the links have been set up /mnt/debhome and /mnt/svn
###################################################

# determine if we are upgrading/reinstalling or first install
if test -f "/tmp/initialise-linux-status"; then
	# get the status, either upgrade or install
	STATUS=`cat "/tmp/initialise-linux-status"`
	
	if test "${STATUS}" = "upgrade"; then
		# check if currentkeyid exists
		if test -f "/mnt/debhome/dists/home/currentkeyid.txt"; then
			# get currentkeyid as /mnt/debhome will be available.
			CURRENTKEYID=`cat /mnt/debhome/dists/home/currentkeyid.txt`
			echo "initialise-linux:postinst:upgrade: CURRENTKEYID = ${CURRENTKEYID}"
			
			# get the new key id from debhomepubkey.gpg
			# as /etc/apt/keyrings/debhomepubkey.gpg will have been replaced with a new one
			if test -f "/etc/apt/keyrings/debhomepubkey.gpg"; then
				# get the new key id
				NEWKEYID=`gpg --show-key "/etc/apt/keyrings/debhomepubkey.gpg" | sed -e '/^[ ]/!d'`
				echo "initialise-linux:postinst:upgrade: NEWKEYID = ${NEWKEYID}"

				# does the new key exist in the key list
				gpg --list-keys "$NEWKEYID" > "/tmp/newkeyerror.txt" 2>&1
				RC=$?
				
				echo "initialise-linux:postinst:upgrade: RC = ${RC} for NEWKEYID in key list"

				if test ${RC} -ne 0; then
					# new key does not exist in the current list
					# delete the public key and the secret key from /mnt/debhome/currentkeyid
					gpg --batch --yes --delete-secret-key "${CURRENTKEYID}"
					gpg --batch --yes --delete-key "${CURRENTKEYID}"
					
					# import the new secret key
					# not necessary to import the public key
					gpg --batch --yes --import --passphrase 'coahtr3552' "/tmp/debhomeseckey.gpg"
					
					# the key has changed sign the repository
					echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
					echo "initialise-linux:postinst:upgrade: The key has changed, run init-linux to sign the repository"
					echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
					read -t 5 value
				else
					# the key has not changed
					echo "initialise-linux:postinst:upgrade: The key has not changed"
				
				fi	

			else
				# /etc/apt/keyrings/debhomepubkey.gpg not found
				# cannot determine the key id
				echo " "
				echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
				echo "postinst: Cannot determine the new key id as /etc/apt/keyrings/debhomepubkey.gpg not found"
				echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
				
				# wait for a prompt or time out of 5 seconds
				read -t 5 value
			fi
		else
			# /mnt/debhome/dists/home/currentkeyid.txt does not exist
			echo " "
			echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
			echo "initialise-linux:postinst:upgrade: /mnt/debhome/dists/home/currentkeyid.txt not found cannot upgrade key"
			echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
			read -t 5 value
		fi
	
    elif test "${STATUS}" = "install"; then
		# this is the first install
		# import the secret key
		if test -f "/tmp/debhomeseckey.gpg"; then
			# secret key exists, import it
			gpg --batch --yes --passphrase 'coahtr3552' --import "/tmp/debhomeseckey.gpg"

			# check the current key id that was used to sign the repository
			if test -f "/mnt/debhome/dists/home/currentkeyid.txt"; then
				# the current key id is available
				CURRENTKEYID=`cat /mnt/debhome/dists/home/currentkeyid.txt`
				echo "initialise-linux:postinst:install: CURRENTKEYID = ${CURRENTKEYID}"

				# get the new key id
				NEWKEYID=`gpg --show-key "/etc/apt/keyrings/debhomepubkey.gpg" | sed -e '/^[ ]/!d'`
				echo "initialise-linux:postinst:install: NEWKEYID = ${NEWKEYID}"

				# if the new key id and the current key id are the same
				# there is no need to sign the repository
				if test "${NEWKEYID} = ${CURRENTKEYID}"; then
					# not necessary to sign the repository
					echo " "
					echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
					echo "initialise-linux:postinst:install: New key = current key"
					echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
					read -t 5 value
				fi
			else
				# /mnt/debhome/dists/home/currentkeyid.txt not found
				# the repository has not been signed
				echo " "
				echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
				echo "initialise-linux:postinst:install: The repository has not been signed."
				echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
				read -t 5 value
			fi
			
		else
			# /tmp/debhomeseckey.gpg not found
			# cannot determine the key id
			echo " "
			echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
			echo "initialise-linux:postinst:install: Cannot determine the key id as /tmp/debhomeseckey.gpg not found"
			echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
			
			# wait for a prompt or time out of 5 seconds
			read -t 5 value
		fi
    fi
else
	# there is no file /tmp/initialise-linux-status
	echo "+++++++++++++++++++++++++++++++++++++++++++++"
	echo "There is no file /tmp/initialise-linux-status"
	echo "initialise-linux:postinst will not run"
	echo "+++++++++++++++++++++++++++++++++++++++++++++"
	read -t 5 value
fi

# exit with code 0, as read -t 5 value may exit with non zero value
exit 0
