#!/usr/bin/bash

##################################################
# get status install or upgrade from /tmp/initialise-linux-status
# which was created by preinst
# 
###################################################

if test -f "/etc/apt/keyrings/debhomepubkey.gpg"; then
	# get the new key id
	NEWKEYID=`gpg --show-key "/etc/apt/keyrings/debhomepubkey.gpg" | sed -e '/^[ ]/!d'`

	# does the new key exist in the key list
	gpg --list-keys | grep -i "$NEWKEYID"

	if test ${?} -ne 0; then
		# new key does not exist in the current list
		# delete the public key and the secret key from /mnt/debhome/currentkeyid
		CURRENTKEYID=`cat /mnt/debhome/currentkeyid`
		gpg --delete-secret-key "${CURRENTKEYID}"
		gpg --delete-key "${CURRENTKEYID}"
		
		# import the new secret key
		# not necessary to import the public key
		gpg --import "/tmp/debhomeseckey.gpg"
	fi
		

else
	# /etc/apt/keyrings/debhomepubkey.gpg not found
	# cannot determine the key id
	echo " "
	echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
	echo "postinst: Cannot determine the new key id as /etc/apt/keyrings/debhomepubkey.gpg not found"
	echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
	
	# wait for a prompt or time out of 10 seconds
	read -t 10 value
fi
