#!/bin/bash
#################################################
# initialise-linux:postrm
#################################################

#################################################
# for remove:
#   get current key id
#	remove debhomepubkey.gpg
#	delete all keys public and secret
#
# for upgrade:
#	store the currentkeyid in a file /tmp/currentkeyid
#   this keyid will be used for deleting the old key if necessary.
#   
# only do this for remove, not upgrade
if test "$1" = "remove"; then

	ARCH=`arch`

	# remove debhomepubkey.gpg and debhome.sources and robert from sudoers.d
	if test -f /etc/apt/keyrings/debhomepubkey.gpg; then
	
		# get the current key for deleting
		# this must be in prerm before debhomepubkey.gpg is removed
		# the repository /mnt/debhome may not be available
		# This is the safest way to get the current key id
		CURRENTKEYID=`gpg --show-key /etc/apt/keyrings/debhomepubkey.gpg | sed -e '/^[ ]/!d'`
		# remove leading spaces from the key
		echo "${CURRENTKEYID}" | sed -e 's/^[ ]*//' > "/tmp/currentkeyid.txt"
		# get the key without leading spaces
		CURRENTKEYID=`cat /tmp/currentkeyid.txt`

		# the secret key and public key may or may not be in the keyring
		# delete the current secret key only if it is in the keyring
		gpg --list-secret-keys "${CURRENTKEYID}" > "/tmp/gpglistkey.txt" 2>&1
		if test $? -eq 0; then
			# delete the keys from the keyring
			echo "initialise-linux:prerm:remove: deleting secret key [${CURRENTKEYID}]"
		
			gpg --batch --yes --pinentry-mode loopback --delete-secret-keys "${CURRENTKEYID}"

			# delete the public key only if the secret key has been deleted
			gpg --batch --yes --delete-keys "${CURRENTKEYID}"
		else
			# key not found
			echo "initialise-linux:prerm:remove: secret key ${CURRENTKEYID} not found in keyring"
		fi
		
		# delete the current public key only if it is in the keyring
		gpg --list-keys "${CURRENTKEYID}" > "/tmp/gpglistkey.txt" 2>&1
		if test $? -eq 0; then
			# delete the public key from the keyring
			echo "initialise-linux:prerm:remove: deleting public key [${CURRENTKEYID}]"
		
			# delete the public key 
			gpg --batch --yes --delete-keys "${CURRENTKEYID}"
		else
			# key not found
			echo "initialise-linux:prerm:remove: public key ${CURRENTKEYID} not found in keyring"
		fi


		# the file debhomepubkey.gpg will be automatically removed when the 
		# package is removed.
	else
		# the file /etc/apt/keyrings/debhomepubkey.gpg does not exist
		# print and error message and continue
		echo "initialise-linux:prerm:remove: The file /etc/apt/keyrings/debhomepubkey.gpg was not found"
		echo "initialise-linux:prerm:remove: The secret and public key could not be deleted"
		read -t 5 value
	fi

	# for rpi
	if test "${ARCH}" = "aarch64"; then
		test -f /etc/apt/sources.list.d/debhome-rpi.list && rm -fv /etc/apt/sources.list.d/debhome-rpi.list
	elif test "${ARCH}" = "x86_64"; then
		# for amd64
		test -f /etc/apt/sources.list.d/debhome-amd64.list && rm -fv /etc/apt/sources.list.d/debhome-amd64.list
	fi

fi
exit 0
