#!/bin/bash
#################################################
# initialise-linux:postrm
#################################################

#################################################
# for remove:
#   get current key id
#	remove debhomepubkey.gpg
#	delete all keys public and secret
#
# for upgrade:
#	store the currentkeyid in a file /tmp/currentkeyid
#   this keyid will be used for deleting the old key if necessary.
#   
# only do this for remove, not upgrade
if test "$1" = "remove"; then

	ARCH=`arch`

	# remove debhomepubkey.gpg and debhome.sources and robert from sudoers.d
	if test -f /etc/apt/keyrings/debhomepubkey.gpg; then
	
		# get the current key for deleting
		# this must be in prerm before debhomepubkey.gpg is removed
		# the repository /mnt/debhome may not be available
		# This is the safest way to get the current key id
		CURRENTKEYID=`gpg --show-key /etc/apt/keyrings/debhomepubkey.gpg | sed -e '/^[ ]/!d'`
		# delete the keys from the keyring
		gpg --batch --yes --delete-secret-keys "${CURRENTKEYID}"

		# delete the public key only if the secret key has been deleted
		gpg --batch --yes --delete-keys "${CURRENTKEYID}"
		
		# the file debhomepubkey.gpg will be automatically removed when the 
		# package is removed.
	else
		# the file /etc/apt/keyrings/debhomepubkey.gpg does not exist
		# print and error message and continue
		echo "initialise-linux:prerm: The file /etc/apt/keyrings/debhomepubkey.gpg was not found"
		echo "initialise-linux:prerm: The secret and public key could not be deleted"
		read -t 5 value
	fi

	# for rpi
	if test "${ARCH}" = "aarch64"; then
		test -f /etc/apt/sources.list.d/debhome-rpi.list && rm -fv /etc/apt/sources.list.d/debhome-rpi.list
	elif test "${ARCH}" = "x86_64"; then
		# for amd64
		test -f /etc/apt/sources.list.d/debhome-amd64.list && rm -fv /etc/apt/sources.list.d/debhome-amd64.list
	fi

elif test "$1" = "upgrade"; then
	# get the currentkeyid for possible deleting by postinst
	if test -f /etc/apt/keyrings/debhomepubkey.gpg; then

		# get currentkeyid from /mnt/debhome/dists/home/currentkeyid.txt
		# as /mnt/debhome repository will be available
		CURRENTKEYID=`cat /mnt/debhome/dists/home/currentkeyid.txt`
	else
		# debhomepubkey.gpg does not exist
		echo "initialise-linux:prerm: Cannot determine current key id, /mnt/debhome/dists/home/currentkeyid.txt not found"
		read -t 5 value
	fi
fi
exit 0
